### ISSUE TITLE
fire two commands in one event in saga

### ISSUE THREAD

**Issue by pawarvijay** [adrai/node-cqrs-saga#30]
### according to current saga [test case flow](https://github.com/adrai/node-cqrs-saga/tree/master/test/integration/fixture/order)
your event sequence is like 
1. orderCreated
2. **then** seatsReserved
3. **then** paymentAccepted
4. **then** orderConfirmed

It is **chained** , each event is depended on previous event except first one.
 
### now in my scenario

i want to create two commands in one event like 

> On **salesInvoiceCreated event**   
> i want   
>  
> **createAccounting command**   &  **createStock command**  To be fired **parallely**

as in my use case those **two commands** are only depended on **salesInvoiceCreated event**  
but but **not on each other**

how can i achieve this ..?

### 1 way that i think

in `module.exports = require('cqrs-saga').defineSaga({      `

```
async.parallel([
    function(callback){
        var cmd = {        
              command: 'createAccounting'  
              //excluded some fields just for demo example                          
              }; 
              saga.addCommandToSend(cmd);
              saga.destroy();
              saga.commit(callback);
    },
    function(callback){
        var cmd = {        
              command: 'createStock'       
              //excluded some fields just for demo example                     
              }; 
              saga.addCommandToSend(cmd);
              saga.destroy();
              saga.commit(callback);
    }
],
function(err, results){ 
});
```
as in [saga test case](https://github.com/adrai/node-cqrs-saga/blob/master/test/integration/fixture/order/orderCreated.js) one saga fires only one command , and for my test case i will fire two commands.

Is it a proper way to implement this scenario in cqrs-saga? or is there any other way ?

**Comment by pawarvijay** [comment]
in all i am trying to fire two commands from one saga

**Comment by adrai** [comment]
no problem... just call `saga.addCommandToSend(cmd);` multiple times before calling `saga.commit(callback);` 1 time

**Comment by pawarvijay** [comment]
:+1: nice test cases ,  i came to know how saga works from[ integration test](https://github.com/adrai/node-cqrs-saga/blob/master/test/integration/integrationTest.js) that uses [these sagas](https://github.com/adrai/node-cqrs-saga/tree/master/test/integration/fixture/order)

**Comment by nanov** [comment]
I have an implementation question regarding kinda the same issue, how do you clean ( ie destroy ) the saga when you have fired multiple events from it ? In chained / one-command you would catch te commands resulting event and destroy the saga? but when you have multiple such? 

One solution is to set the number of dispatched commands in the saga itself, and then deduct one  on each event, but I am not sure how will this solution behave in a high concurrency scenario, as the deduction is not atomic ( something like that is done : saga.set('commands',saga.get('commands',-1) ).

Am i missing something here, or i should handle this in some kind of a maintenance process?

**Comment by adrai** [comment]
Your solution is exactly what we do most of the time in this cases...
