### ISSUE TITLE
handling domain failures in saga

### ISSUE THREAD

**Issue by pawarvijay** [adrai/node-cqrs-saga#31]
- Based on your integration test of saga ,  i understand the timeout scenario and the way it is handled by issuing cancel order command.

- how do we handle failures which result in to "rejectedCommand" Event for any command issued by saga?

- how can i make my saga listen to this "rejectedCommand" Event

- Eg: in your test cases suppose if payment fails because of some business rules and we get "rejectedCommand" Event , how should we handle this in saga ?

**Comment by adrai** [comment]
something like this:

``` javascript
module.exports = require('cqrs-saga').defineSaga({// event to match..
  name: 'commandRejected', // optional, default is file name without extension
  aggregate: 'payment',
  context: 'sale',
  version: 2, // default is 0
  containingProperties: ['payload.transactionId'],
  id: 'payload.transactionId',
  existing: true // if true it will check if there is already a saga in the db and only if there is something it will continue...
  // payload: 'payload' // if not defined it will pass the whole event...
  // priority: 1 // optional, default Infinity, all sagas will be sorted by this value
}, function (evt, saga, callback) {

  var cmd = {
    // id: 'my own command id', // if you don't pass an id it will generate one, when emitting the command...
    name: 'cancelOrder',
    aggregate: {
      name: 'order',
      id: saga.get('orderId')
    },
    context: {
      name: 'sale'
    },
    payload: {
      transactionId: saga.id
    },
    meta: evt.meta // to transport userId...   if not defined in cmd, it will defaultly use it from event
  };

  saga.addCommandToSend(cmd);

  saga.commit(callback);
}).defineShouldHandle(function (evt, saga) {
  return evt.payload.command.name === 'pay';
});
```

**Comment by pawarvijay** [comment]
Thanks @adrai  this will do :+1: 

Does this also means that for every aggregate 
wherever i want to handle "commandRejected" event 
i need to create this kind of saga (with aggregate & context defined if any) **FOR THAT AGGREGATE** ?

**Comment by adrai** [comment]
Yes



Il giorno 25-feb-2016, alle ore 07:34, vijay pawar <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Thanks @adrai<https://github.com/adrai> this will do [:+1:]

Does this also means that for every aggregate
wherever i want to handle "commandRejected" event
i need to create this kind of saga (with aggregate & context defined if any) FOR THAT AGGREGATE ?

-
