### ISSUE TITLE
MongoDB >=2.0.0 driver support

### ISSUE THREAD

**Issue by repkins** [adrai/node-cqrs-saga#35]
Hello, @adrai !

I came across with issue running sagas using with newer mongodb versions. Apparenlty it does not work with new auto reconnect feature anymore starting with version of 2.0. So there associated driver still uses old deprecated auto reconnect variant which apparently has been removed in MongoDB.

P.S. Most likely in other cqrs-ddd related NPM packages also have this issue.

**Comment by adrai** [comment]
Try new version: https://github.com/adrai/node-cqrs-saga/compare/v1.6.25...v1.6.26

**Comment by repkins** [comment]
Oh, great. Thanks!
