### ISSUE TITLE
Using Saga to pass configuration data to infrastructure layers used by domains

### ISSUE THREAD

**Issue by josh0707** [adrai/node-cqrs-saga#36]
Hello,
Thank you for the module.

I need to send email notifications when a specific event has been triggered.

**I have this scenario:**
userCreated -> Saga -> createEmailNotification -> EmailNotification Domain -> emailNotificationCreated -> Saga -> sendEmail -> Email Domain -> emailSent

To create the email notification, the EmailNotification Domain requires: user_email_address, email_template_id, email_templates_path, application_url

**Problem:** 
I can get the user_email_address from the userCreated event. However, how to pass the other informations to the domain?

**Solution 1:** 
1. pass an application_id as a userCreated event meta
2. pass the application_id as a createEmailNotification command meta
3. In EmailNotification Domain pass the application_id to the infrastructure layer in charge of creating the email. The infrastructure layer will fetch the application configuration file based on the application_id

**Solution 2 (involves an ApplicationConfiguration Domain):**
1. pass an application_id as a userCreated event meta
2. In Saga, issue a getApplicationConfiguration command with application_id as meta
3. In Saga, listen to gotApplicationConfiguration event, then pass a createEmailNotification with all the information needed as payload.
4. In EmailNotification Domain pass all the information to the infrastructure layer in charge of creating the email. 

Since a command should be issued to modified a state, solution 2 does not seem to be a good solution as it only issue a command to read the state.

**Solution 3 (involves an ApplicationConfiguration Domain):**
1. pass an application_id as a userCreated event meta
2. In Saga, connect to the ApplicationConfiguration event store and rebuild the state of the aggregate based on the aggregate_id to get the application configuration
3. In Saga, pass a createEmailNotification with all the information needed as payload.
4. In EmailNotification Domain pass all the information to the infrastructure layer in charge of creating the email. 

Based on your experience, what would be the best solution, or is there another, more efficient way to pass configuration data for infrastructure layers used by domains?

Thanks,

Josh

**Comment by adrai** [comment]
Hi Josh,

Probably I'm totally wrong but why so complicated?
Why not having a dedicated ReadModel which the saga (or other event handlers) can query to get all information needed to send an email?

i.e. have a denormalizer component responsible to prepare the ReadModel and then in eventExtenders or in a saga component (or an other service) send the email?

sorry, but perhaps I miss something ;-)

**Comment by josh0707** [comment]
Thank you for your input.
I want to capture "emailSent" events in the event store. I would create an Email Domain Model, receiving "sendEmail" commands and returning "emailSent" events.

**I guess my question is** "how to pass or access specific application settings" needed to perform some operations in a domain (ie. sending an email would require the infrastructure layer to have application data such as an api key for external providers, application url...)".

Should I have an Applicationconfiguration Domain and...:

1. Solution 1
Use an EventDenormalizer to create a ReadModel? This read model would then be used by the Application service listening to "userCreated" events to trigger a "sendEmail" command.

2. Solution 2
Get Saga to listen to "applicationCongifugarionSet" events to persist the information while waiting for "userCreated" events in order to trigger "sendEmail" commands.
As far as I understood, in a CQRS DDD, Saga should not query any read model as there is no guaranty the data is up to date.

Or any other idea to pass application settings to domains?

**Comment by adrai** [comment]
If the Application settings are static, why not just have them as env or loaded via json file as config?

If the Application settings are dynamic it's ok to have a saga to query a ReadModel... so solution 1 sounds ok...

btw: So you want sendMail to be a command, right? and that command should generate the event emailSent... does that mean that the email was really sent or is it more a sendEmailRequested?

**Comment by josh0707** [comment]
The application settings are dynamic.
I should go with An applicationConfiguration Domain listening to "setApplicationConfiguration" commands and generating "applicationConfigurationSet" events.
An Eventdenormalizer would create a ReadModel used by Saga to retrieve the required data to send the email.

Regarding the "emailSent" event, it would be generated in the Email Domain (creation of the email based on a template and call of an external service - i.e. MailGun - for the delivery.

"sendEmailRequested" might be more appropriate than "emailSent", with the Email Domain listening for "delivered" events from the service (when the service can provide them) before generating an "emailSent" event.
However, not all external services provide delivery confirmation. So, for now, I am fine considering the email has been sent when it reaches the service, even if an error occurs during the delivery.
